# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals sacharla

steps:
- checkout: self
  persistCredentials: true
- script: |
    git clone https://$(token)@github.com/JorgeAmbrocio/sa-test-azure-pipeline.git
  displayName: 'clonning repository'
- script: |
    cd sa-test-azure-pipeline/server
    npm install
    npm test
  displayName: 'run install modules and test'
- script:  |
    docker rm -f satest
    docker rmi satesti
  displayName: 'remove container and image'
  continueOnError: true
- script: |
    cd sa-test-azure-pipeline/server
    docker build -t satesti .
  displayName: 'build container'
- script: |
    docker run -d -p 3211:3210 --name satest satesti
  displayName: 'run container'
